### Verbo GET – listar
GET http://localhost:8000/produto/0 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/4 HTTP/1.1

content-type: application/json
{
"id" : 1,
"nome" : "Patel de Flango",
"descricao" : "Um delicioso pastel de flango",
"foto" : null,
"valor_unitario" : 12 
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1

content-type: application/json
{
"id" : 2,
"nome" : "Patel de Strogonoff",
"descricao" : "Um delicioso pastel de Strogonoff ao molho pardo",
"foto" : null,
"valor_unitario" : 20
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1
