### Verbo GET – listar
GET http://localhost:8000/cliente/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
"nome" : "Denian de Souza Rosa",
"matricula" : "12345",
"cpf" : "08494877908",
"telefone" : "49991622867",
"grupo" : 1,
"senha" : "denian"
}


### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
"nome" : "Denian Souza",
"matricula" : "12345",
"cpf" : "08484975401",
"telefone" : "49991622867",
"grupo" : 2,
"senha" : "souza"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
